<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ZoneSeeder extends Seeder
{
    public function run(): void
    {
        $zones = [
            // United States (country_id: 223)
            ['zone_id' => 1, 'zone_country_id' => 223, 'zone_code' => 'AL', 'zone_name' => 'Alabama'],
            ['zone_id' => 2, 'zone_country_id' => 223, 'zone_code' => 'AK', 'zone_name' => 'Alaska'],
            ['zone_id' => 3, 'zone_country_id' => 223, 'zone_code' => 'AS', 'zone_name' => 'American Samoa'],
            ['zone_id' => 4, 'zone_country_id' => 223, 'zone_code' => 'AZ', 'zone_name' => 'Arizona'],
            ['zone_id' => 5, 'zone_country_id' => 223, 'zone_code' => 'AR', 'zone_name' => 'Arkansas'],
            ['zone_id' => 7, 'zone_country_id' => 223, 'zone_code' => 'AA', 'zone_name' => 'AA'],
            ['zone_id' => 9, 'zone_country_id' => 223, 'zone_code' => 'AE', 'zone_name' => 'AE'],
            ['zone_id' => 11, 'zone_country_id' => 223, 'zone_code' => 'AP', 'zone_name' => 'AP'],
            ['zone_id' => 12, 'zone_country_id' => 223, 'zone_code' => 'CA', 'zone_name' => 'California'],
            ['zone_id' => 13, 'zone_country_id' => 223, 'zone_code' => 'CO', 'zone_name' => 'Colorado'],
            ['zone_id' => 14, 'zone_country_id' => 223, 'zone_code' => 'CT', 'zone_name' => 'Connecticut'],
            ['zone_id' => 15, 'zone_country_id' => 223, 'zone_code' => 'DE', 'zone_name' => 'Delaware'],
            ['zone_id' => 16, 'zone_country_id' => 223, 'zone_code' => 'DC', 'zone_name' => 'District of Columbia'],
            ['zone_id' => 17, 'zone_country_id' => 223, 'zone_code' => 'FM', 'zone_name' => 'Federated States Of Micronesia'],
            ['zone_id' => 18, 'zone_country_id' => 223, 'zone_code' => 'FL', 'zone_name' => 'Florida'],
            ['zone_id' => 19, 'zone_country_id' => 223, 'zone_code' => 'GA', 'zone_name' => 'Georgia'],
            ['zone_id' => 20, 'zone_country_id' => 223, 'zone_code' => 'GU', 'zone_name' => 'Guam'],
            ['zone_id' => 21, 'zone_country_id' => 223, 'zone_code' => 'HI', 'zone_name' => 'Hawaii'],
            ['zone_id' => 22, 'zone_country_id' => 223, 'zone_code' => 'ID', 'zone_name' => 'Idaho'],
            ['zone_id' => 23, 'zone_country_id' => 223, 'zone_code' => 'IL', 'zone_name' => 'Illinois'],
            ['zone_id' => 24, 'zone_country_id' => 223, 'zone_code' => 'IN', 'zone_name' => 'Indiana'],
            ['zone_id' => 25, 'zone_country_id' => 223, 'zone_code' => 'IA', 'zone_name' => 'Iowa'],
            ['zone_id' => 26, 'zone_country_id' => 223, 'zone_code' => 'KS', 'zone_name' => 'Kansas'],
            ['zone_id' => 27, 'zone_country_id' => 223, 'zone_code' => 'KY', 'zone_name' => 'Kentucky'],
            ['zone_id' => 28, 'zone_country_id' => 223, 'zone_code' => 'LA', 'zone_name' => 'Louisiana'],
            ['zone_id' => 29, 'zone_country_id' => 223, 'zone_code' => 'ME', 'zone_name' => 'Maine'],
            ['zone_id' => 30, 'zone_country_id' => 223, 'zone_code' => 'MH', 'zone_name' => 'Marshall Islands'],
            ['zone_id' => 31, 'zone_country_id' => 223, 'zone_code' => 'MD', 'zone_name' => 'Maryland'],
            ['zone_id' => 32, 'zone_country_id' => 223, 'zone_code' => 'MA', 'zone_name' => 'Massachusetts'],
            ['zone_id' => 33, 'zone_country_id' => 223, 'zone_code' => 'MI', 'zone_name' => 'Michigan'],
            ['zone_id' => 34, 'zone_country_id' => 223, 'zone_code' => 'MN', 'zone_name' => 'Minnesota'],
            ['zone_id' => 35, 'zone_country_id' => 223, 'zone_code' => 'MS', 'zone_name' => 'Mississippi'],
            ['zone_id' => 36, 'zone_country_id' => 223, 'zone_code' => 'MO', 'zone_name' => 'Missouri'],
            ['zone_id' => 37, 'zone_country_id' => 223, 'zone_code' => 'MT', 'zone_name' => 'Montana'],
            ['zone_id' => 38, 'zone_country_id' => 223, 'zone_code' => 'NE', 'zone_name' => 'Nebraska'],
            ['zone_id' => 39, 'zone_country_id' => 223, 'zone_code' => 'NV', 'zone_name' => 'Nevada'],
            ['zone_id' => 40, 'zone_country_id' => 223, 'zone_code' => 'NH', 'zone_name' => 'New Hampshire'],
            ['zone_id' => 41, 'zone_country_id' => 223, 'zone_code' => 'NJ', 'zone_name' => 'New Jersey'],
            ['zone_id' => 42, 'zone_country_id' => 223, 'zone_code' => 'NM', 'zone_name' => 'New Mexico'],
            ['zone_id' => 43, 'zone_country_id' => 223, 'zone_code' => 'NY', 'zone_name' => 'New York'],
            ['zone_id' => 44, 'zone_country_id' => 223, 'zone_code' => 'NC', 'zone_name' => 'North Carolina'],
            ['zone_id' => 45, 'zone_country_id' => 223, 'zone_code' => 'ND', 'zone_name' => 'North Dakota'],
            ['zone_id' => 46, 'zone_country_id' => 223, 'zone_code' => 'MP', 'zone_name' => 'Northern Mariana Islands'],
            ['zone_id' => 47, 'zone_country_id' => 223, 'zone_code' => 'OH', 'zone_name' => 'Ohio'],
            ['zone_id' => 48, 'zone_country_id' => 223, 'zone_code' => 'OK', 'zone_name' => 'Oklahoma'],
            ['zone_id' => 49, 'zone_country_id' => 223, 'zone_code' => 'OR', 'zone_name' => 'Oregon'],
            ['zone_id' => 50, 'zone_country_id' => 223, 'zone_code' => 'PW', 'zone_name' => 'Palau'],
            ['zone_id' => 51, 'zone_country_id' => 223, 'zone_code' => 'PA', 'zone_name' => 'Pennsylvania'],
            ['zone_id' => 52, 'zone_country_id' => 223, 'zone_code' => 'PR', 'zone_name' => 'Puerto Rico'],
            ['zone_id' => 53, 'zone_country_id' => 223, 'zone_code' => 'RI', 'zone_name' => 'Rhode Island'],
            ['zone_id' => 54, 'zone_country_id' => 223, 'zone_code' => 'SC', 'zone_name' => 'South Carolina'],
            ['zone_id' => 55, 'zone_country_id' => 223, 'zone_code' => 'SD', 'zone_name' => 'South Dakota'],
            ['zone_id' => 56, 'zone_country_id' => 223, 'zone_code' => 'TN', 'zone_name' => 'Tennessee'],
            ['zone_id' => 57, 'zone_country_id' => 223, 'zone_code' => 'TX', 'zone_name' => 'Texas'],
            ['zone_id' => 58, 'zone_country_id' => 223, 'zone_code' => 'UT', 'zone_name' => 'Utah'],
            ['zone_id' => 59, 'zone_country_id' => 223, 'zone_code' => 'VT', 'zone_name' => 'Vermont'],
            ['zone_id' => 60, 'zone_country_id' => 223, 'zone_code' => 'VI', 'zone_name' => 'Virgin Islands'],
            ['zone_id' => 61, 'zone_country_id' => 223, 'zone_code' => 'VA', 'zone_name' => 'Virginia'],
            ['zone_id' => 62, 'zone_country_id' => 223, 'zone_code' => 'WA', 'zone_name' => 'Washington'],
            ['zone_id' => 63, 'zone_country_id' => 223, 'zone_code' => 'WV', 'zone_name' => 'West Virginia'],
            ['zone_id' => 64, 'zone_country_id' => 223, 'zone_code' => 'WI', 'zone_name' => 'Wisconsin'],
            ['zone_id' => 65, 'zone_country_id' => 223, 'zone_code' => 'WY', 'zone_name' => 'Wyoming'],

            // Canada (country_id: 38)
            ['zone_id' => 66, 'zone_country_id' => 38, 'zone_code' => 'AB', 'zone_name' => 'Alberta'],
            ['zone_id' => 67, 'zone_country_id' => 38, 'zone_code' => 'BC', 'zone_name' => 'British Columbia'],
            ['zone_id' => 68, 'zone_country_id' => 38, 'zone_code' => 'MB', 'zone_name' => 'Manitoba'],
            ['zone_id' => 69, 'zone_country_id' => 38, 'zone_code' => 'NF', 'zone_name' => 'Newfoundland'],
            ['zone_id' => 70, 'zone_country_id' => 38, 'zone_code' => 'NB', 'zone_name' => 'New Brunswick'],
            ['zone_id' => 71, 'zone_country_id' => 38, 'zone_code' => 'NS', 'zone_name' => 'Nova Scotia'],
            ['zone_id' => 72, 'zone_country_id' => 38, 'zone_code' => 'NT', 'zone_name' => 'Northwest Territories'],
            ['zone_id' => 73, 'zone_country_id' => 38, 'zone_code' => 'NU', 'zone_name' => 'Nunavut'],
            ['zone_id' => 74, 'zone_country_id' => 38, 'zone_code' => 'ON', 'zone_name' => 'Ontario'],
            ['zone_id' => 75, 'zone_country_id' => 38, 'zone_code' => 'PE', 'zone_name' => 'Prince Edward Island'],
            ['zone_id' => 76, 'zone_country_id' => 38, 'zone_code' => 'QC', 'zone_name' => 'Quebec'],
            ['zone_id' => 77, 'zone_country_id' => 38, 'zone_code' => 'SK', 'zone_name' => 'Saskatchewan'],
            ['zone_id' => 78, 'zone_country_id' => 38, 'zone_code' => 'YT', 'zone_name' => 'Yukon Territory'],

            // Germany (country_id: 81)
            ['zone_id' => 79, 'zone_country_id' => 81, 'zone_code' => 'NDS', 'zone_name' => 'Niedersachsen'],
            ['zone_id' => 80, 'zone_country_id' => 81, 'zone_code' => 'BAW', 'zone_name' => ''],
            ['zone_id' => 81, 'zone_country_id' => 81, 'zone_code' => 'BAY', 'zone_name' => 'Bayern'],
            ['zone_id' => 82, 'zone_country_id' => 81, 'zone_code' => 'BER', 'zone_name' => 'Berlin'],
            ['zone_id' => 83, 'zone_country_id' => 81, 'zone_code' => 'BRG', 'zone_name' => 'Brandenburg'],
            ['zone_id' => 84, 'zone_country_id' => 81, 'zone_code' => 'BRE', 'zone_name' => 'Bremen'],
            ['zone_id' => 85, 'zone_country_id' => 81, 'zone_code' => 'HAM', 'zone_name' => 'Hamburg'],
            ['zone_id' => 86, 'zone_country_id' => 81, 'zone_code' => 'HES', 'zone_name' => 'Hessen'],
            ['zone_id' => 87, 'zone_country_id' => 81, 'zone_code' => 'MEC', 'zone_name' => 'Mecklenburg-Vorpommern'],
            ['zone_id' => 88, 'zone_country_id' => 81, 'zone_code' => 'NRW', 'zone_name' => 'Nordrhein-Westfalen'],
            ['zone_id' => 89, 'zone_country_id' => 81, 'zone_code' => 'RHE', 'zone_name' => 'Rheinland-Pfalz'],
            ['zone_id' => 90, 'zone_country_id' => 81, 'zone_code' => 'SAR', 'zone_name' => 'Saarland'],
            ['zone_id' => 91, 'zone_country_id' => 81, 'zone_code' => 'SAS', 'zone_name' => 'Sachsen'],
            ['zone_id' => 92, 'zone_country_id' => 81, 'zone_code' => 'SAC', 'zone_name' => 'Sachsen-Anhalt'],
            ['zone_id' => 93, 'zone_country_id' => 81, 'zone_code' => 'SCN', 'zone_name' => 'Schleswig-Holstein'],
            ['zone_id' => 94, 'zone_country_id' => 81, 'zone_code' => 'THE', 'zone_name' => ''],

            // Austria (country_id: 14)
            ['zone_id' => 95, 'zone_country_id' => 14, 'zone_code' => 'WI', 'zone_name' => 'Wien'],
            ['zone_id' => 96, 'zone_country_id' => 14, 'zone_code' => 'NO', 'zone_name' => ''],
            ['zone_id' => 97, 'zone_country_id' => 14, 'zone_code' => 'OO', 'zone_name' => ''],
            ['zone_id' => 98, 'zone_country_id' => 14, 'zone_code' => 'SB', 'zone_name' => 'Salzburg'],
            ['zone_id' => 99, 'zone_country_id' => 14, 'zone_code' => 'KN', 'zone_name' => ''],
            ['zone_id' => 100, 'zone_country_id' => 14, 'zone_code' => 'ST', 'zone_name' => 'Steiermark'],
            ['zone_id' => 101, 'zone_country_id' => 14, 'zone_code' => 'TI', 'zone_name' => 'Tirol'],
            ['zone_id' => 102, 'zone_country_id' => 14, 'zone_code' => 'BL', 'zone_name' => 'Burgenland'],
            ['zone_id' => 103, 'zone_country_id' => 14, 'zone_code' => 'VB', 'zone_name' => 'Voralberg'],

            // Switzerland (country_id: 204)
            ['zone_id' => 104, 'zone_country_id' => 204, 'zone_code' => 'AG', 'zone_name' => 'Aargau'],
            ['zone_id' => 105, 'zone_country_id' => 204, 'zone_code' => 'AI', 'zone_name' => 'Appenzell Innerrhoden'],
            ['zone_id' => 106, 'zone_country_id' => 204, 'zone_code' => 'AR', 'zone_name' => 'Appenzell Ausserrhoden'],
            ['zone_id' => 107, 'zone_country_id' => 204, 'zone_code' => 'BE', 'zone_name' => 'Bern'],
            ['zone_id' => 108, 'zone_country_id' => 204, 'zone_code' => 'BL', 'zone_name' => 'Basel-Landschaft'],
            ['zone_id' => 109, 'zone_country_id' => 204, 'zone_code' => 'BS', 'zone_name' => 'Basel-Stadt'],
            ['zone_id' => 110, 'zone_country_id' => 204, 'zone_code' => 'FR', 'zone_name' => 'Freiburg'],
            ['zone_id' => 111, 'zone_country_id' => 204, 'zone_code' => 'GE', 'zone_name' => 'Genf'],
            ['zone_id' => 112, 'zone_country_id' => 204, 'zone_code' => 'GL', 'zone_name' => 'Glarus'],
            ['zone_id' => 113, 'zone_country_id' => 204, 'zone_code' => 'GR', 'zone_name' => 'Graubuenden'],
            ['zone_id' => 114, 'zone_country_id' => 204, 'zone_code' => 'JU', 'zone_name' => 'Jura'],
            ['zone_id' => 115, 'zone_country_id' => 204, 'zone_code' => 'LU', 'zone_name' => 'Luzern'],
            ['zone_id' => 116, 'zone_country_id' => 204, 'zone_code' => 'NE', 'zone_name' => 'Neuenburg'],
            ['zone_id' => 117, 'zone_country_id' => 204, 'zone_code' => 'NW', 'zone_name' => 'Nidwalden'],
            ['zone_id' => 118, 'zone_country_id' => 204, 'zone_code' => 'OW', 'zone_name' => 'Obwalden'],
            ['zone_id' => 119, 'zone_country_id' => 204, 'zone_code' => 'SG', 'zone_name' => 'St. Gallen'],
            ['zone_id' => 120, 'zone_country_id' => 204, 'zone_code' => 'SH', 'zone_name' => 'Schaffhausen'],
            ['zone_id' => 121, 'zone_country_id' => 204, 'zone_code' => 'SO', 'zone_name' => 'Solothurn'],
            ['zone_id' => 122, 'zone_country_id' => 204, 'zone_code' => 'SZ', 'zone_name' => 'Schwyz'],
            ['zone_id' => 123, 'zone_country_id' => 204, 'zone_code' => 'TG', 'zone_name' => 'Thurgau'],
            ['zone_id' => 124, 'zone_country_id' => 204, 'zone_code' => 'TI', 'zone_name' => 'Tessin'],
            ['zone_id' => 125, 'zone_country_id' => 204, 'zone_code' => 'UR', 'zone_name' => 'Uri'],
            ['zone_id' => 126, 'zone_country_id' => 204, 'zone_code' => 'VD', 'zone_name' => 'Waadt'],
            ['zone_id' => 127, 'zone_country_id' => 204, 'zone_code' => 'VS', 'zone_name' => 'Wallis'],
            ['zone_id' => 128, 'zone_country_id' => 204, 'zone_code' => 'ZG', 'zone_name' => 'Zug'],
            ['zone_id' => 129, 'zone_country_id' => 204, 'zone_code' => 'ZH', 'zone_name' => ''],

            // Spain (country_id: 195)
            ['zone_id' => 130, 'zone_country_id' => 195, 'zone_code' => '', 'zone_name' => ''],
            ['zone_id' => 131, 'zone_country_id' => 195, 'zone_code' => 'Alava', 'zone_name' => 'Alava'],
            ['zone_id' => 132, 'zone_country_id' => 195, 'zone_code' => 'Albacete', 'zone_name' => 'Albacete'],
            ['zone_id' => 133, 'zone_country_id' => 195, 'zone_code' => 'Alicante', 'zone_name' => 'Alicante'],
            ['zone_id' => 134, 'zone_country_id' => 195, 'zone_code' => 'Almeria', 'zone_name' => 'Almeria'],
            ['zone_id' => 135, 'zone_country_id' => 195, 'zone_code' => 'Asturias', 'zone_name' => 'Asturias'],
            ['zone_id' => 136, 'zone_country_id' => 195, 'zone_code' => 'Avila', 'zone_name' => 'Avila'],
            ['zone_id' => 137, 'zone_country_id' => 195, 'zone_code' => 'Badajoz', 'zone_name' => 'Badajoz'],
            ['zone_id' => 138, 'zone_country_id' => 195, 'zone_code' => 'Baleares', 'zone_name' => 'Baleares'],
            ['zone_id' => 139, 'zone_country_id' => 195, 'zone_code' => 'Barcelona', 'zone_name' => 'Barcelona'],
            ['zone_id' => 140, 'zone_country_id' => 195, 'zone_code' => 'Burgos', 'zone_name' => 'Burgos'],
            ['zone_id' => 141, 'zone_country_id' => 195, 'zone_code' => 'Caceres', 'zone_name' => 'Caceres'],
            ['zone_id' => 142, 'zone_country_id' => 195, 'zone_code' => 'Cadiz', 'zone_name' => 'Cadiz'],
            ['zone_id' => 143, 'zone_country_id' => 195, 'zone_code' => 'Cantabria', 'zone_name' => 'Cantabria'],
            ['zone_id' => 144, 'zone_country_id' => 195, 'zone_code' => 'Castellon', 'zone_name' => 'Castellon'],
            ['zone_id' => 145, 'zone_country_id' => 195, 'zone_code' => 'Ceuta', 'zone_name' => 'Ceuta'],
            ['zone_id' => 146, 'zone_country_id' => 195, 'zone_code' => 'Ciudad Real', 'zone_name' => 'Ciudad Real'],
            ['zone_id' => 147, 'zone_country_id' => 195, 'zone_code' => 'Cordoba', 'zone_name' => 'Cordoba'],
            ['zone_id' => 148, 'zone_country_id' => 195, 'zone_code' => 'Cuenca', 'zone_name' => 'Cuenca'],
            ['zone_id' => 149, 'zone_country_id' => 195, 'zone_code' => 'Girona', 'zone_name' => 'Girona'],
            ['zone_id' => 150, 'zone_country_id' => 195, 'zone_code' => 'Granada', 'zone_name' => 'Granada'],
            ['zone_id' => 151, 'zone_country_id' => 195, 'zone_code' => 'Guadalajara', 'zone_name' => 'Guadalajara'],
            ['zone_id' => 152, 'zone_country_id' => 195, 'zone_code' => 'Guipuzcoa', 'zone_name' => 'Guipuzcoa'],
            ['zone_id' => 153, 'zone_country_id' => 195, 'zone_code' => 'Huelva', 'zone_name' => 'Huelva'],
            ['zone_id' => 154, 'zone_country_id' => 195, 'zone_code' => 'Huesca', 'zone_name' => 'Huesca'],
            ['zone_id' => 155, 'zone_country_id' => 195, 'zone_code' => 'Jaen', 'zone_name' => 'Jaen'],
            ['zone_id' => 156, 'zone_country_id' => 195, 'zone_code' => 'La Rioja', 'zone_name' => 'La Rioja'],
            ['zone_id' => 157, 'zone_country_id' => 195, 'zone_code' => 'Las Palmas', 'zone_name' => 'Las Palmas'],
            ['zone_id' => 158, 'zone_country_id' => 195, 'zone_code' => 'Leon', 'zone_name' => 'Leon'],
            ['zone_id' => 159, 'zone_country_id' => 195, 'zone_code' => 'Lleida', 'zone_name' => 'Lleida'],
            ['zone_id' => 160, 'zone_country_id' => 195, 'zone_code' => 'Lugo', 'zone_name' => 'Lugo'],
            ['zone_id' => 161, 'zone_country_id' => 195, 'zone_code' => 'Madrid', 'zone_name' => 'Madrid'],
            ['zone_id' => 162, 'zone_country_id' => 195, 'zone_code' => 'Malaga', 'zone_name' => 'Malaga'],
            ['zone_id' => 163, 'zone_country_id' => 195, 'zone_code' => 'Melilla', 'zone_name' => 'Melilla'],
            ['zone_id' => 164, 'zone_country_id' => 195, 'zone_code' => 'Murcia', 'zone_name' => 'Murcia'],
            ['zone_id' => 165, 'zone_country_id' => 195, 'zone_code' => 'Navarra', 'zone_name' => 'Navarra'],
            ['zone_id' => 166, 'zone_country_id' => 195, 'zone_code' => 'Ourense', 'zone_name' => 'Ourense'],
            ['zone_id' => 167, 'zone_country_id' => 195, 'zone_code' => 'Palencia', 'zone_name' => 'Palencia'],
            ['zone_id' => 168, 'zone_country_id' => 195, 'zone_code' => 'Pontevedra', 'zone_name' => 'Pontevedra'],
            ['zone_id' => 169, 'zone_country_id' => 195, 'zone_code' => 'Salamanca', 'zone_name' => 'Salamanca'],
            ['zone_id' => 170, 'zone_country_id' => 195, 'zone_code' => 'Santa Cruz de Tenerife', 'zone_name' => 'Santa Cruz de Tenerife'],
            ['zone_id' => 171, 'zone_country_id' => 195, 'zone_code' => 'Segovia', 'zone_name' => 'Segovia'],
            ['zone_id' => 172, 'zone_country_id' => 195, 'zone_code' => 'Sevilla', 'zone_name' => 'Sevilla'],
            ['zone_id' => 173, 'zone_country_id' => 195, 'zone_code' => 'Soria', 'zone_name' => 'Soria'],
            ['zone_id' => 174, 'zone_country_id' => 195, 'zone_code' => 'Tarragona', 'zone_name' => 'Tarragona'],
            ['zone_id' => 175, 'zone_country_id' => 195, 'zone_code' => 'Teruel', 'zone_name' => 'Teruel'],
            ['zone_id' => 176, 'zone_country_id' => 195, 'zone_code' => 'Toledo', 'zone_name' => 'Toledo'],
            ['zone_id' => 177, 'zone_country_id' => 195, 'zone_code' => 'Valencia', 'zone_name' => 'Valencia'],
            ['zone_id' => 178, 'zone_country_id' => 195, 'zone_code' => 'Valladolid', 'zone_name' => 'Valladolid'],
            ['zone_id' => 179, 'zone_country_id' => 195, 'zone_code' => 'Vizcaya', 'zone_name' => 'Vizcaya'],
            ['zone_id' => 180, 'zone_country_id' => 195, 'zone_code' => 'Zamora', 'zone_name' => 'Zamora'],
            ['zone_id' => 181, 'zone_country_id' => 195, 'zone_code' => 'Zaragoza', 'zone_name' => 'Zaragoza'],

            // Military / Armed Forces (country_id: 250)
            ['zone_id' => 182, 'zone_country_id' => 250, 'zone_code' => 'AA', 'zone_name' => 'AA'],
            ['zone_id' => 183, 'zone_country_id' => 250, 'zone_code' => 'AE', 'zone_name' => 'AE'],
            ['zone_id' => 184, 'zone_country_id' => 250, 'zone_code' => 'AP', 'zone_name' => 'AP'],
        ];

        // Insert in chunks of 50 to avoid query size limits
        foreach (array_chunk($zones, 50) as $chunk) {
            DB::table('zones')->insertOrIgnore($chunk);
        }
    }
}
