[PHP]
; display_errors = off
date.timezone = "UTC"

max_execution_time = 320
max_input_time = 60
memory_limit = 1024M

upload_max_filesize = 50M
post_max_size = 50M
; session.save_handler = memcached
; session.save_path = "memcached:11211"
; session.gc_maxlifetime = 10800
