version: '3.7'
services:

  php:
    build:
      context: ${PWD}/
    environment:
      APP_ENV: dev
    depends_on:
      - mysql
    volumes:
      - "./:/var/www"
    ports:
      - "9280:80"

  mysql:
    build:
      context: ${PWD}/docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_DATABASE: "docker"
    ports:
      - "9206:3306"

  mail:
    image: mailhog/mailhog
    ports:
      - "9225:8025"
