version: 2

jobs:
  build:
    working_directory: ~/cakephp-app
    docker:

      - image: circleci/php:5.6-apache-stretch-node-browsers-legacy
        environment:
          - APP_ENV: circle

      - image: circleci/mariadb:10.3-ram
        environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_ROOT_HOST=%
          - MYSQL_USER=ubuntu
          - MYSQL_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
        command:
          mysqld --sql-mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y mysql-client libmcrypt-dev libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
      - run: sudo docker-php-ext-install pdo_mysql mcrypt intl gd soap sockets

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - Vendor

      - run: ./bin/set-owner
      - run: ./bin/set-configs "$APP_ENV"
      - run: ./bin/writedirs
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Run Code Sniffs
          command: ./bin/run-codesniffer y
      - run:
          name: Run tests
          command: ./bin/run-tests All -d memory_limit=512M
      - run:
          name: Run Code Coverage
          command: ./bin/coverage-ensure 67
